from enum import Enum

class DecisionCode(str, Enum):
    # --- 21.1 Data & Calendar ---
    NON_TRADING_DAY = "NON_TRADING_DAY"
    WAITING_MARKET_DATA = "WAITING_MARKET_DATA"
    DATASET_INCOMPLETE = "DATASET_INCOMPLETE"
    MARKET_BAR_INVALID = "MARKET_BAR_INVALID"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"

    # --- 21.2 Manifest ---
    APPROVED = "APPROVED"
    SCHEMA_INVALID = "SCHEMA_INVALID"
    INTEGRITY_INVALID = "INTEGRITY_INVALID"
    ISSUER_NOT_TRUSTED = "ISSUER_NOT_TRUSTED"
    MANIFEST_NOT_YET_VALID = "MANIFEST_NOT_YET_VALID"
    MANIFEST_EXPIRING_SOON = "MANIFEST_EXPIRING_SOON"
    MANIFEST_EXPIRED = "MANIFEST_EXPIRED"
    MANIFEST_REVOKED = "MANIFEST_REVOKED"
    MANIFEST_MISSING = "MANIFEST_MISSING"
    STRATEGY_MISMATCH = "STRATEGY_MISMATCH"
    STRATEGY_VERSION_MISMATCH = "STRATEGY_VERSION_MISMATCH"
    PARAMS_CANONICALIZATION_MISMATCH = "PARAMS_CANONICALIZATION_MISMATCH"
    PARAMS_HASH_MISMATCH = "PARAMS_HASH_MISMATCH"
    APPROVAL_ID_MISMATCH = "APPROVAL_ID_MISMATCH"
    EXECUTION_MODE_NOT_ALLOWED = "EXECUTION_MODE_NOT_ALLOWED"
    RISK_ACTION_NOT_ALLOWED = "RISK_ACTION_NOT_ALLOWED"

    # --- 21.3 Orders & Risk ---
    ORDER_LIMIT_EXCEEDED = "ORDER_LIMIT_EXCEEDED"
    DAILY_BUY_LIMIT_EXCEEDED = "DAILY_BUY_LIMIT_EXCEEDED"
    MAX_OPEN_POSITIONS_EXCEEDED = "MAX_OPEN_POSITIONS_EXCEEDED"
    INSUFFICIENT_CASH = "INSUFFICIENT_CASH"
    SELL_WITHOUT_POSITION = "SELL_WITHOUT_POSITION"
    DUPLICATE_INTENT = "DUPLICATE_INTENT"
    BROKER_REJECTED = "BROKER_REJECTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"

    # --- 21.4 Accounting & Reconciliation ---
    RECONCILE_OK = "RECONCILE_OK"
    CASH_BALANCE_MISMATCH = "CASH_BALANCE_MISMATCH"
    POSITION_QUANTITY_MISMATCH = "POSITION_QUANTITY_MISMATCH"
    MISSING_LEDGER_ENTRY = "MISSING_LEDGER_ENTRY"
    DUPLICATE_LEDGER_ENTRY = "DUPLICATE_LEDGER_ENTRY"
    FIFO_ALLOCATION_MISMATCH = "FIFO_ALLOCATION_MISMATCH"
    REALIZED_PNL_MISMATCH = "REALIZED_PNL_MISMATCH"
